## K-nearest neighbour classification algorithm model

In [106]:
# Importing all necessary packages
import matplotlib

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
import matplotlib.pyplot as plt

from matplotlib.colors import ListedColormap

import numpy as np
import pandas as pd 
import joblib as extractor

Importing the data from the CSV dataset using Pandas

In [107]:
dataframe = pd.read_csv("data/person-age-gender-games-dataset.csv")

Standarising the dataset by changing the male and female as 0 and 1 for KNN classification algo

In [108]:
dataframe['Gender'] = dataframe['Gender'].replace({"female": 0, "male": 1})
dataframe.head()

Person  Age  Gender Favorite Game
0  Person 1   20       1       Cricket
1  Person 2    3       1      Football
2  Person 3    5       1       Cricket
3  Person 4   30       1       Cricket
4  Person 5   45       0      Football

Spliting the features and label to x and y variable

In [109]:
x = dataframe.drop(columns=['Person','Favorite Game'])
y = dataframe['Favorite Game']

Spliting the train data and the test data from the given dataset

In [110]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1)

Initialising the KNN classifier and fitting the training data to train the model

In [111]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

 Predicting the model by the test data

In [112]:
predict = knn.predict(x_test)
print(predict)
print("Accuracy : " + str(accuracy_score(y_test, predict)))
print("Confusion Matrix : \n" + str(confusion_matrix(y_test, predict)))

extractor.dump(knn,"KNN Person sport interest - model.joblib")

['Cricket' 'Football' 'Wrestle' 'Wrestle']
Accuracy : 0.5
Confusion Matrix : 
[[0 0 1]
 [1 1 0]
 [0 0 1]]


['KNN Player Detection model.joblib']